# Generated by Django 5.0.6 on 2024-06-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('file', models.CharField(max_length=100)),
                ('code_structure', models.CharField(max_length=1000)),
                ('assessment_criteria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('points', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lite.project')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField()),
                ('revisions', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lite.checkpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('comment', models.CharField(max_length=2000)),
                ('date_time', models.DateTimeField()),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lite.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lite.user')),
            ],
        ),
    ]
